name: Staging CI
on:
  push:
    branches: [staging]

env:
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Installing the nodejs with 18 version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: sudo docker build -t $DOCKER_USER/hellonodejs:github .
      - run: sudo docker push bromx/hellonodejs:github
